### ISSUE TITLE
Button lock might cause removal of text property.

### ISSUE THREAD

**Issue by thomasf** [rolandwalker/button-lock#3]
Two examples of this problem:
- (rear-nonsticky  t) is removed from the end of many comint prompts, ielm is an example that is very common.
- I cannot edit the first character in a wdired buffer when fixmee-mode is enabled. The space before the first file name character also loses the (rear-nonsticky  read-only) property.

It  is actually fixmee-mode that I am using, I chose to post the bug report here anyway.

I am not 100% sure that this library is the culprit but it happens the moment i enable fixmee-mode.

**Comment by rolandwalker** [comment]
This should be fixed by #4.

I was surprised to find that variable `font-lock-extra-managed-props` is not buffer-local.  We now make it local in the buffers for which we modify it.  Thus, the effects should no longer spill over into wdired buffers.

This was included in release 1.0.2, which was just tagged, and should percolate out to MELPA-stable soon.

**Comment by thomasf** [comment]
nice catch!
